image:
  file: .gitpod.Dockerfile

tasks:
  - init: dotnet restore --ignore-failed-sources -s https://nuget.pkg.github.com/marsoffice/index.json -s https://api.nuget.org/v3/index.json
    command: dotnet build -c Debug
    env:
      AZURE_FUNCTIONS_ENVIRONMENT: Development
      ASPNETCORE_ENVIRONMENT: Development

ports:
  - port: 7000
    onOpen: ignore

vscode:
  extensions:
    - muhammad-sammy.csharp
    - vscode-icons-team.vscode-icons
    - esbenp.prettier-vscode