name: qeeps-access
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      # - name: setup net5
      #   uses: actions/setup-dotnet@v1.8.1
      #   with:
      #     dotnet-version: '5.x'

      - name: setup netcore3.1
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: '3.1.x'

      - name: cache nuget
        uses: actions/cache@v2
        id: cache-nuget
        env:
          cache-name: cache-nuget
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: dotnet publish
        run: dotnet publish -c Release -o ./dist

      - name: upload artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist
          path: ./dist

  deploy_stg:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: stg
    name: deploy stg
    steps:
      - name: download artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: 'dist'
          path: ./dist

          
      - name: az login
        uses: Azure/login@v1
        with:
          creds: |
              {
                "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
              }
            
      - name: deploy westeurope
        uses: Azure/functions-action@v1.3.2
        with:
          package: ./dist
          app-name: func-${{ github.workflow }}-westeurope-stg
          
  deploy_prod:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: prod
    name: deploy prod
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: 'dist'
          path: ./dist
          
      - name: az login
        uses: Azure/login@v1
        with:
          creds: |
              {
                "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
                "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
                "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
                "tenantId": "${{ secrets.AZURE_TENANT_ID }}"
              }

      - name: deploy westeurope
        uses: Azure/functions-action@v1.3.2
        with:
          package: ./dist
          app-name: func-${{ github.workflow }}-westeurope-prod
